version: "3.1"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: media
    ports:
      - "3030:3030"
