version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: dev
      PORT: 3001

  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: admin

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media
    ports:
      - "5432:5432"