version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    command: npm run start
    ports: 
      - 3001:3001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3001

  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: admin

  postgres:
    image: postgres:latest
    ports:
      - 3333:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media
volumes: 
 data: {}
